services:
  - type: web
    name: vectorify-backend
    env: python
    rootDir: .
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
